### PR TITLE
Fix typo "Github" in Localizable.strings

### PR DESCRIPTION
**Pull request by NoRi2909**
## Summary

As GitHub is a brand name, the camel-case "H" should be kept.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

Noticed this in Lokalise as a translator added a respective comment.

### CODE REVIEW

**Review by bgoncal — APPROVED** [review]
Thanks! make sure this is also update in Localize

**Comment by NoRi2909** [comment]
> Thanks! make sure this is also update in Localize

Doesn't the merge auto-update the English string in Lokalise?

**Comment by bgoncal** [comment]
It needs to be updated in lokalise as well

**Comment by NoRi2909** [comment]
But I can't edit the English string in Lokalise, only the German translation I'm working on.

When I do a PR on Core or Frontend the Merge process automatically updates the affected strings in Lokalise.
If that is not the case for the iOS app – I cannot do that …?

**Comment by bgoncal** [comment]
I'll check on Monday for you, perhaps I can make the change

**Pull request merged**
