### PR TITLE
Use user agent for all webviews (fixes #2512)

### LINKED ISSUE #2512: User Agent not Modified for Authentication
**Device model, version and app version**

Model Name: N/A (virtual machine that thinks it is an iMac Pro)
macOS Version: 10.15.7
App Version: 2023.7
Safari Version: 13.1.3 (15609.4.1)

**Home Assistant Core Version**
2023.12.4 (but also not relevant)

**Describe the bug**
On the initial login/onboarding screen just after typing in the Home Assistant server URL, the webview that opens does not have `Home Assistant` in the user agent.

**To Reproduce**
Simply point the initial onboarding Home Assistant URL to any webserver where you can see the user agent. For quick testing in Nginx you can do:
```nginx
return 200 $http_user_agent;
```

**Expected behavior**
This webview should append/prepend `Home Assistant` to the user agent as it does with other requests (see #632).

**Screenshots**
N/A

**Additional context**
I plan to make a simple user agent match pattern in my reverse proxy to only allow companion apps.

### PR DESCRIPTION
**Pull request by DaAwesomeP**
## Summary

Not all webviews (in particular the onboarding one) currently use the custom user agent. This adds the user agent used elsewhere in the app. This PR adds the user agent (same one used in the main webview) to the other webviews.

## Screenshots

N/A

## Link to pull request in Documentation repository

N/A

## Any other notes

Fixes #2512

I copied the user agent used that is already used here for the main webview.:
https://github.com/home-assistant/iOS/blob/8127b055fccaf595cd289e19c8d0b6e2e9ebfe85/Sources/App/WebView/WebViewController.swift#L146-L147

### CODE REVIEW

**Comment by bgoncal** [comment]
Can you elaborate a little more on the use case, like, how differently are you handling nginx for web/mobile?

**Comment by DaAwesomeP** [comment]
> Can you elaborate a little more on the use case, like, how differently are you handling nginx for web/mobile?

@bgoncal Yes, that's exactly it. I am allowing only the Home Assistant apps (by user agent) outside of my local network from Nginx.

**Comment by bgoncal** [comment]
I have one small suggestions to move this app name user agent to one single place insteac of repeating it everywhere, I tried to commit but you need to allow maintainer to commit on your PR: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Otherwise here is my changes that you could also copy:
https://github.com/home-assistant/iOS/compare/pr/2728?expand=1

**Review by bgoncal — CHANGES_REQUESTED** [review]
After this small change we can merge it

**Comment by DaAwesomeP** [comment]
@bgoncal ah, sorry about that. I merged your change into my branch.

**Review by bgoncal — APPROVED** [review]
Thank you for your contribution! 🚀

**Pull request merged**
