### PR TITLE
Change mdi icons for floors ascended and descended

### PR DESCRIPTION
**Pull request by gerard33**
There are new stairs up and down icons available and these are part of HA 0.105
https://materialdesignicons.com/icon/stairs-up
https://materialdesignicons.com/icon/stairs-down

### CODE REVIEW

**Comment by TomBrien** [comment]
This will be a breaking change for anyone who's phone automatically updates but isn't running >0.105.

**Comment by gerard33** [comment]
That's true, but only when re-installing the mobile app integration isn't it? Otherwise the existing entities and mdi icons will not be updated. And I guess using the latest version of HA is always recommended?

**Comment by TomBrien** [comment]
Hopefully @robbiet480 can confirm but I’m pretty sure the icon is set which each sensor update. See the similar code for battery icons and BSSID

**Comment by robbiet480** [comment]
Yeah I don't really like this since it could cause icons to go missing if people are on older versions of HA. Not opposed to merging this at some point, but let's just wait until 0.105 has been out in the world for more than a few weeks.

**Comment by robbiet480** [comment]
It’s been long enough I feel comfortable merging this, but to be safe can you modify this a bit to set the icon based on the HA version? If you aren’t a Swift dev I can do it, just let me know!

**Comment by gerard33** [comment]
Not a Swift dev so would be great if you can add that check.

**Comment by robbiet480** [comment]
Closing in favor of #678

**Pull request closed without merging**
