### PR TITLE
Fix link to actions documentation on the web

### PR DESCRIPTION
**Pull request by theomega**
The previous URL for the documentation was wrong and leading to a 404.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @theomega, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;iOS#588).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by TomBrien** [comment]
I've added a redirect server side to fix this. Just waiting for the cache to clear

**Comment by TomBrien** [comment]
@theomega is the link working for you now?

**Comment by theomega** [comment]
Yes, it does. Shall we still merge this PR or close it?

**Comment by TomBrien** [comment]
That good. I think we should leave it open. That address was never valid, so let's not rely on a redirect where possible. Will leave for Robbie to decide

**Pull request merged**
