### PR TITLE
Download core strings to iOS proj

### PR DESCRIPTION
**Pull request by bgoncal**
## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Review by zacwest — APPROVED** [review]

**Comment by ulrikjo** [comment]
With no summary or notes, what does this achieve other than creating extra strings to translate in Lokalise?

**Comment by bgoncal** [comment]
> With no summary or notes, what does this achieve other than creating extra strings to translate in Lokalise?

This shouldn't bring new strings to translate, this brings Core lokalise project strings to iOS project so those strings can be used in the App aswell, the need came within the CarPlay PR.

**Comment by ulrikjo** [comment]
> This shouldn't bring new strings to translate, this brings Core lokalise project strings to iOS project so those strings can be used in the App aswell, the need came within the CarPlay PR.

Oh, sorry then! 267 new strings were just added to Lokalise. I assumed they came from this.

**Comment by bgoncal** [comment]
> > This shouldn't bring new strings to translate, this brings Core lokalise project strings to iOS project so those strings can be used in the App aswell, the need came within the CarPlay PR.
> 
> Oh, sorry then! 267 new strings were just added to Lokalise. I assumed they came from this.

Perhaps you were right, I see the strings there indeed, I will see what went wrong

**Pull request merged**
