### PR TITLE
Concept of Assist on Apple Watch

### PR DESCRIPTION
**Pull request by bgoncal**
## Summary
Goal:
- Use Assist on an intuitive way in Apple Watch

Achieved on this PR:
- Conversation with Assist is working

Challenge:
- ~Since SFSpeechRecognizer is not available on the watchOS I have use (for demonstration purposes) the keyboard dictation, which is not good since you need extra taps. One alternative could be record the audio in the Apple Watch and process over the iPhone, but performance would need to be tested.~
  -> I am now recording the audio on watchOS and processing it on iOS

Also pending:
- Having to open the app to trigger Assist is not ideal, so the best we could do in watchOS (considering Apple limitations) is to ~provide a complication that directly opens Assist~. (Done ✔️ check third demo video)
- Depending on how important the minimum watchOS version requirement is currently, we could drop support to a few versions so we can refactor the code and maybe even use swiftUI to simplify navigation and interaction.

~Why not demo it on a real Apple Watch?
- ~Currently my devices are running iOS and watchOS beta's and I couldn't make them quickly work with home assistant project yet.~
 -> I have added a new demo video showing it working on a real device + fully by voice (currently you still need to "end" the session manually)

## Screenshots

https://github.com/home-assistant/iOS/assets/5808343/db58f6ea-f0df-4055-8522-1811c46d8e79

https://github.com/home-assistant/iOS/assets/5808343/e40fd00f-4c91-451e-b2a2-eeeebf855561

https://github.com/home-assistant/iOS/assets/5808343/c896d854-0831-4ce3-9c5f-aa103d36e950

### CODE REVIEW

**Comment by cpvbruno** [comment]
Also, another todo item that just popped on my mind is to try to use Apple Watch Ultra action button to open Assist directly

**Comment by cpvbruno** [comment]
I did one more iteration, now it is possible to launch assist via complication and also it automatically stops recording on silence.

https://github.com/home-assistant/iOS/assets/5808343/c53c7fd6-8c0a-4ec1-8707-8ea9c8b22fd2

**Comment by jrspowers** [comment]
Hallo, kan ik deze app ergens testen voor Apple Watch? Dit is erg handig!

**Comment by cpvbruno** [comment]
> Hallo, kan ik deze app ergens testen voor Apple Watch? Dit is erg handig!

Hey, if you know how to compile an iOS app you can try right away using this branch, otherwise I still need to find time to wrap it up and check with Nabu Casa if the feature matches their expectations (since Android already has it, I would need to align the UI and behavior)

**Comment by bgoncal** [comment]
I'm closing this draft PR, I will open another one based on this but using HA Assist pipeline directly through HA Websocket API

**Pull request closed without merging**
