### PR TITLE
Add Apple Watch battery sensor

### PR DESCRIPTION
**Pull request by bgoncal**
## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by TomBrien** [comment]
This seems to be rounding to nearest 5 %. Is that expected?

**Comment by bgoncal** [comment]
> This seems to be rounding to nearest 5 %. Is that expected? 

It looks like the API returns changes every 5% change indeed.
(Unless I rounded it somehow and didn't notice, but that's the values that the API were outputting for me while debugging too)

**Comment by bgoncal** [comment]
@TomBrien I just noticed that iPhone battery behaves the same

**Comment by TomBrien** [comment]
Oh so it does. Never noticed that...

**Pull request merged**
