### PR TITLE
Use same variable for status bar color as frontend

### PR DESCRIPTION
**Pull request by bgoncal**
## Summary

Reopening this PR now that https://github.com/home-assistant/frontend/pull/20758 is implemented

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by bgoncal** [comment]
I'm currently manually testing this since the previous time there were edge cases around it.

**Comment by oerix** [comment]
> I'm currently manually testing this since the previous time there were edge cases around it.

Any update on this please? I'm still seeing a solid dark background behind the status bar.

**Comment by bgoncal** [comment]
@oerix What theme are you using?

**Comment by oerix** [comment]
> @oerix What theme are you using? What app version?

I'm using my own custom theme with translucency. I did test @Nezz's [visionos](https://github.com/Nezz/homeassistant-visionos-theme) theme, and having the same issue.

App version: 2024.6 (2024.696)

**Comment by bgoncal** [comment]
> > @oerix What theme are you using? What app version?
> 
> 
> 
> I'm using my own custom theme with translucency. I did test @Nezz's [visionos](https://github.com/Nezz/homeassistant-visionos-theme) theme, and having the same issue.
> 
> 
> 
> App version: 2024.6 (2024.696) 

Transparency is not expected to work with this PR, this is just to align which variable is used by front end and app to tint the status bar.

What you are asking for is a new feature, where the header would start from the top of the screen and have its content offset by the top safe area, please open a feature request for that at Home Assistant community

**Pull request closed without merging**
