### PR TITLE
Write android application record to NFC tags.

### PR DESCRIPTION
**Pull request by JayNewstrom**
Relates to https://github.com/home-assistant/android/issues/876
Relates to https://github.com/home-assistant/android/pull/969

This fixes an issue where on certain Android devices a dialog was showing up when scanning the NFC tags.

After this change, scanned NFC tags go directly into the home assistant android companion app.

I was not able to test this locally, but I should be able to tomorrow.

### CODE REVIEW

**Comment by JayNewstrom** [comment]
I don't have an easy way to test this, since I don't have a non personal developer account. 

Screen Shot 2020-09-23 at 9 52 04 AM

If it's possible, could someone else test this for me? I've got some iOS dev friends I could reach out to to help me, but the turn around time will likely be slow due to COVID.

**Comment by zacwest** [comment]
I can give this a try probably sometime before the meeting. I'd also like it to support excluding this Android bit if it's getting close to the length limits, which I can do quickly but might be harder for you in the codebase.

**Comment by JayNewstrom** [comment]
@zacwest feel free to take this over! If there's anything else you want or need from me, let me know.

**Comment by zacwest** [comment]
Implemented as linked above, thanks for getting the ball rolling!

**Pull request closed without merging**
