### PR TITLE
client cert: Fix build

### PR DESCRIPTION
**Pull request by PatentLobster**
## Summary
See [!2144](https://github.com/home-assistant/iOS/pull/2144)
## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by zacwest** [comment]
Likely this just needs master merged in since the optionally of these things changed in the ios 16 sdk and that's fixed all the way around on master. Out of curiosity are you running that branch? Shoes is work well for you?

**Comment by PatentLobster** [comment]
@zacwest Yes I'm on this branch for a while praying it will get merged lol I really need mtls.

I had some trouble compiling the watch app (clibsodium module unknown) so I removed it all together, I actually have 0 experience in swift or ios development for that matter, took me a couple days to understand how to compile it I probably did it wrong but it's stable

**Comment by zacwest** [comment]
Cool. Watch required a new architecture in Xcode 14, that's why you hit it. If you build the branch as is in 13 it would work but not to a newer phone. I'll update that branch when I get a chance. Watch won't really work right now with client certificates because Apple limits the technology so you aren't missing much.

**Comment by PatentLobster** [comment]
Thanks @zacwest! 

fortunately I don't have the watch, I did try to merge this branch with master but didn't know how to handle code conflicts since I never touched swift before 😜

**Pull request closed without merging**
