### PR TITLE
Add BuildMaterialDesignIconsFont to codegen build phases

### PR DESCRIPTION
**Pull request by bgoncal**
## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

**Comment by zacwest** [comment]
How expensive is the script execution when it noops? I think I made it fast but I don't remember.

**Comment by bgoncal** [comment]
> How expensive is the script execution when it noops? I think I made it fast but I don't remember. 
> 

I need to check, something weird happened in the pipelines, nothing related to the script was merged but the material design .json file was not in the runner machine anymore... then I found this script but I couldn't find where it was being triggered before, was it manually only?

**Comment by zacwest** [comment]
Podfile executes it

**Comment by bgoncal** [comment]
> Podfile executes it

Ok, good heads up then, I will check why pod install is not generating those files in the runner machine

**Pull request merged**
